
module.exports = {
    MIN_RANGED_ATTACK_RADIUS_SQUARED: 16,
    MAX_RANGED_ATTACK_RADIUS_SQUARED: 49,
    MAX_MAGIC_ATTACK_RADIUS_SQUARED: 36,
    MAGIC_ATTACK_SPLASH_PERCENTAGE: .25,
    MAX_MELEE_ATTACK_RADIUS_SQUARED: 2,
    SENSE_EXIT_THRESHOLD: 144,
    PLAYER_MOVE_DELAY: 2,
    PLAYER_MELEE_POWER: 6,
    PLAYER_MELEE_DELAY: 2,
    PLAYER_MAGIC_POWER: 4,
    PLAYER_MAGIC_DELAY: 4,
    PLAYER_RANGED_POWER: 6,
    PLAYER_RANGED_DELAY: 3
};