module.exports = {
    PRIMARY_ENEMY: "primary",
    NUM_PRIMARY_ENEMIES: "numPrimaryEnemies",
    SECONDARY_ENEMY: "secondary",
    NUM_SECONDARY_ENEMIES: "numSecondaryEnemies",
    SWARM_ENEMY: "swarm",
    NUM_SWARM_ENEMIES: "numSwarm",
    RARE_ENEMY: "rare",
    NUM_RARE_ENEMIES: "numRare",
    BOSS_ENEMY: "boss",
    NUM_BOSS_ENEMIES: "numBoss",
    ENEMY_DENSITY: 'enemyDensity',
    TERRAIN_DENSITY: "terrainDensity",
    TERRAIN_FILL: "terrainFill",
    ROUND_LIMIT: "roundLimit",
    PRIMARY_OPEN_TERRAIN: "primaryOpenTerrain",
    SECONDARY_OPEN_TERRAIN: "secondaryOpenTerrain",
    PRIMARY_IMPASSIBLE_TERRAIN: "primaryImpassibleTerrain",
    SECONDARY_IMPASSIBLE_TERRAIN: "secondaryImpassibleTerrain"
};